### ISSUE TITLE
使用pyfr报错

### ISSUE THREAD

**Issue by arbaleast** [icexmoon/file-remark#1]
```
Traceback (most recent call last):
  File "d:\env\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\env\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Env\python\Scripts\pyfr.exe\__main__.py", line 4, in <module>
  File "d:\env\python\lib\site-packages\file_remark\__main__.py", line 4, in <module>
    from .main import Main
  File "d:\env\python\lib\site-packages\file_remark\main.py", line 4, in <module>
    from file_remark.module.m_files import MFiles
  File "d:\env\python\lib\site-packages\file_remark\module\m_files.py", line 3, in <module>
    from file_remark.my_db import MyDB
  File "d:\env\python\lib\site-packages\file_remark\my_db.py", line 10, in <module>
    class MyDB:
  File "d:\env\python\lib\site-packages\file_remark\my_db.py", line 115, in MyDB
    def __get_multi_sqls(self, file_name: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```
❯ python -V
Python 3.8.8
❯ systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List

OS Name             : Microsoft Windows 11 Pro
OS Version          : 10.0.22000 N/A Build 22000

**Comment by arbaleast** [comment]
请问这是哪出错了

**Comment by hy6544** [comment]
不清楚这个pyfr啥的，我用vscode开发的，源码调试的话可以用加载模块的方式，如果需要的话我可以上传调试样例代码。

**Comment by hy6544** [comment]
我好像搞错了，还以为你说的另一个东西，等我明天debug一下再回复你。

**Comment by icexmoon** [comment]
我排查了一下，这边并没有你遇到的问题，似乎是你的python版本太低，没有支持相关的注解语法导致的，你可以升级python到最新后试一下。
我这边还发现了一个其他的bug，我会打包后上传到pypi，你可以尝试更新。

**Comment by arbaleast** [comment]
> 我排查了一下，这边并没有你遇到的问题，似乎是你的python版本太低，没有支持相关的注解语法导致的，你可以升级python到最新后试一下。 我这边还发现了一个其他的bug，我会打包后上传到pypi，你可以尝试更新。

好的，我更新试试

**Comment by arbaleast** [comment]
```
❯ pyfr
d .git
d .github
- .travis.yml
d doc
- LICENSE
- plug.png
- plug.vim
- README.md
d test
Exception ignored in: <function MyDB.__del__ at 0x000002ACEB4F2200>
Traceback (most recent call last):
  File "d:\env\python\lib\site-packages\file_remark\my_db.py", line 97, in __del__
AttributeError: 'super' object has no attribute '__del__'、
❯ python -V
Python 3.10.4
```
似乎出现新的问题了

**Comment by icexmoon** [comment]
这个就是我说的发现的新bug，已经修复，你更新就行，其实是断开数据库连接后的一个bug，不影响功能。

**Comment by arbaleast** [comment]
行，谢谢

**Comment by icexmoon** [comment]
> 行，谢谢

哈哈，这个应用都已经被我遗忘了。。。居然还真有人用，感觉用处不大。最近打算写一个用来给文件分类的应用，我的download文件夹里一堆各种文件。。。
